version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: cfb_pg
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cfb_network
  mlearning:
    build:
      context: ../
      dockerfile: docker/ml.Dockerfile
    container_name: cfb_ml
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../ml:/usr/app:ro
    restart: always
    command: sleep infinity
    depends_on:
      - postgres
    networks:
      - cfb_network

networks:
  cfb_network:
    driver: bridge